kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-backup-pv
  labels:
    role: es-backup
    access: multi
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  rbd:
    monitors:
      - ceph-node01:6789
      - ceph-node02:6789
      - ceph-node03:6789
    pool: system
    image: es
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
