apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-backup-backend-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      role: es-backup-backend
