apiVersion: v1
kind: Service
metadata:
  name: es-backup-nfs-server
  labels:
    app.kubernetes.io/name: "esbackup"
    app.kubernetes.io/component: elasticsearch-backup-server
spec:
  clusterIP: None
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
  selector:
    app.kubernetes.io/name: "esbackup"
    app.kubernetes.io/component: elasticsearch-backup-server
